### PR TITLE
Merging upstream kanisterio/kanister

### PR DESCRIPTION
**Pull request by pavannd1**
Doing this to experiment with Kopia changes.

### CODE REVIEW

**Comment by julio-lopez** [comment]
We may want maintain a clean branch here and ensure that it is a "fast-forward".
Let me double check a couple of things.

**Review by julio-lopez — CHANGES_REQUESTED** [review]
We may want maintain a clean branch here and ensure that it is a "fast-forward".
Let me double check a couple of things.

**Comment by pavannd1** [comment]
This is what I did
```
pdevaraj @ ~/Work/Kasten/hq/kanister - [sync_master] $ git pull git@github.com:kanisterio/kanister.git master
From github.com:kanisterio/kanister
 * branch            master     -> FETCH_HEAD
Updating 1155bae..bf7e4e5
Fast-forward
...
...
```

**Comment by julio-lopez** [comment]
@pavannd1 Yes, on your side things are good.
I just want to make sure github does a fast forward when the PR is merged instead of explicitly creating a merge commit.

**Comment by julio-lopez** [comment]
AFAICT, there's no way of doing a `--fast-forward` in a PR. We can directly fast-forward master to keep it in sync with upstream. Does that make sense?

https://help.github.com/en/articles/about-merge-methods-on-github

**Comment by julio-lopez** [comment]
Mmm, updating `master` auto-closed this PR.

**Comment by pavannd1** [comment]
I like this better. I guess we can use that method for upstream syncs.

**Pull request merged**
